# Generated by Django 3.2.12 on 2023-04-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_rename_full_name_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacheraccount',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subject', to='Api.subject'),
        ),
    ]
