# Generated by Django 3.2.12 on 2023-04-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_teacheraccount_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='first_name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='surname'),
        ),
        migrations.AddField(
            model_name='teacheraccount',
            name='first_name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='teacheraccount',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='surname'),
        ),
    ]
