# Generated by Django 3.2.12 on 2023-04-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20230413_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheraccount',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.teacheraccount'),
        ),
    ]
